direction: right;
# <- property
#        ^ punctuation.delimiter
#          ^ string
#               ^ punctuation.delimiter

shape: oval
# <- error
#      ^ string

baaaz.style: {
  # <- variable
  #   ^ property
  fill: red
  # <- property
  #     ^ string
}

foo: Label {
  shape: oval
  # <- property
  #      ^ string

  style.fill: red;
  # <- property
  #     ^ property 
}


foo: {
  style: {
    opacity: 0.5
    #        ^ float
    fill: red
    #     ^ string
    stroke: 'red'
    #       ^ string
    stroke-width: 5
    #             ^ number
    shadow: true
    #       ^ boolean
    animated: false
    #         ^ boolean
  }
}
