a <- b <-> c -- d -> e
# <- variable
# ^ operator
#    ^ variable
#      ^ operator
#          ^ variable
#            ^ operator
#               ^ variable
#                 ^ operator
#                    ^ variable

a ----- b
# ^ operator

a ----> b
# ^ operator

a <---- b
# ^ operator

a <---> b
# ^ operator

a.b.c --> d.e
# <- constant
# ^ constant
#   ^ variable
#     ^ operator
#         ^ constant
#           ^ variable



