direction: right;
# <- property
#        ^ punctuation.delimiter
#          ^ string
#               ^ punctuation.delimiter

shape: oval
# <- error
#      ^ error

baaaz.style: {
  # <- variable
  #   ^ property
  fill: red
  # <- property
  #     ^ string
}

foo: Label {
  shape: oval
  # <- property
  #      ^ string

  style.fill: red;
  # <- property
  #     ^ property 
}

