direction: right;
# <- keyword
#        ^ punctuation.delimiter
#          ^ string
#               ^ punctuation.delimiter

shape: oval;
# <- error
#      ^ error

baaaz.style: {
  # <- variable
  #   ^ keyword
  fill: red
  # <- keyword
  #     ^ string
}

foo: Label {
  shape: oval
  # <- keyword
  #      ^ string

  style.fill: red;
  # <- keyword
  #     ^ keyword 
}

