foo.baz.biz
# <- variable
#  ^ punctuanion.delimiter
#   ^ variable
#      ^ punctuanion.delimiter
#       ^ variable

foo: Foo Bar
# <- variable
#  ^ punctuanion.delimiter
#    ^ string

foo: Foo Bar {
  # <- variable
  #  ^ label
  #          ^ punctuation.delimiter

  bar.baz
  # <- variable
  #   ^ variable
}
