foo.'baz'.biz
# <- constant
#  ^ punctuation.delimiter
#   ^ string.special
#        ^ punctuation.delimiter
#         ^ variable

'biz': 'Baz'
# <- string
#      ^ string

foo: Foo Bar
# <- variable
#  ^ punctuation.delimiter
#    ^ string

foo: Foo Bar {
  # <- constant
  #  ^ string
  #          ^ punctuation.bracket

  bar.baz
  # <- constant
  #   ^ variable
}
# <- punctuation.bracket
