foo.'baz'.biz
# <- constant
#  ^ punctuation.delimiter
#   ^ string
#     ^ string
#        ^ punctuation.delimiter
#         ^ variable

"b\nz"
# ^ string.escape
#  ^ string.escape

'b\nz'
# ^ string
#  ^ string

'biz': "Baz\nBiz"
# <- string
#      ^ string
#        ^ string
#           ^ string.escape

foo: Foo Bar
# <- variable
#  ^ punctuation.delimiter
#    ^ text.title

foo: Foo Bar {
  # <- constant
  #  ^ text.title
  #          ^ punctuation.bracket

  bar.baz
  # <- constant
  #   ^ variable
}
# <- punctuation.bracket
